### ISSUE TITLE
用两个栈实现队列

### ISSUE THREAD

**Issue by Petterpx** [Blue-knife/ShelfData#1]
<img width="978" alt="image" src="https://user-images.githubusercontent.com/41142188/177031359-1522cacc-81ec-4a84-8a0c-2566a9c5e991.png">

原题链接：https://leetcode.cn/problems/yong-liang-ge-zhan-shi-xian-dui-lie-lcof/

```kotlin
class CQueue() {

    fun appendTail(value: Int) {

    }

    fun deleteHead(): Int {

    }

}

/**
 * Your CQueue object will be instantiated and called as such:
 * var obj = CQueue()
 * obj.appendTail(value)
 * var param_2 = obj.deleteHead()
 */
```

**Comment by Petterpx** [comment]
<img width="972" alt="image" src="https://user-images.githubusercontent.com/41142188/177031829-2ed11999-0f35-4486-be4a-9476c3644da9.png">

**Comment by LvKang-insist** [comment]
/**
 * @name Demo
 * @package
 * @author 345 QQ:1831712732
 * @time 2022/07/03 16:35
 * @description 思路：栈：先进后出，队列：先进先出。
 *              写入的时候第一个栈正常压入，读取时将第一个栈元素出栈，压入到第二栈中。就能完成先进先出。
 *              注意读取时需要等到第二个栈为空时重新压入
 */

class CQueue() {
    private val stackOne = Stack<Int>()
    private val stackTwo = Stack<Int>()

    fun appendTail(value: Int) {
        stackOne.push(value)
    }

    fun deleteHead(): Int {
        if (stackTwo.isNotEmpty()) {
            return stackTwo.pop()
        } else if (stackOne.isNotEmpty()) {
            while(stackOne.isNotEmpty()) {
                stackTwo.push(stackOne.pop())
            }
            return stackTwo.pop()
        }
        return -1
    }
}

**Comment by LvKang-insist** [comment]
```
/**
 * @name Demo
 * @package
 * @author 345 QQ:1831712732
 * @time 2022/07/03 16:35
 * @description 思路：栈：先进后出，队列：先进先出。
 *              写入的时候第一个栈正常压入，读取时将第一个栈元素出栈，压入到第二栈中。就能完成先进先出。
 *              注意读取时需要等到第二个栈为空时重新压入
 */

class CQueue() {
    private val stackOne = Stack<Int>()
    private val stackTwo = Stack<Int>()

    fun appendTail(value: Int) {
        stackOne.push(value)
    }

    fun deleteHead(): Int {
        if (stackTwo.isNotEmpty()) {
            return stackTwo.pop()
        } else if (stackOne.isNotEmpty()) {
            while(stackOne.isNotEmpty()) {
                stackTwo.push(stackOne.pop())
            }
            return stackTwo.pop()
        }
        return -1
    }
}
```

**Comment by XJ-Up** [comment]
```kotlin
class CQueue() {
    /*思路：创建两个栈：输入栈、输出栈，
            添加数据时添加到输入栈里，
            每次 deleteHead 时，若输出栈为空则将输入栈的数据全部放入输出栈，
            这样输出栈从栈顶往栈底的顺序就是队列从队首往队尾的顺序。
     *
     */
    val inStack = Stack<Int>()
    val outStack = Stack<Int>()

    fun appendTail(value: Int) {
        inStack.push(value)
    }

    fun deleteHead(): Int =
        if (outStack.isNotEmpty()) {
            outStack.pop()
        } else {
            while (inStack.isNotEmpty()) {
                outStack.push(inStack.pop())
            }
            if (outStack.isEmpty()) -1 else outStack.pop()
        }
}
```
